Version 2
PeculiarVentures/fortify-tools pull request #101
Opened 2024-04-18 16:00 UTC by OleksandrSPV

2024-04-23 14:15 UTC, donskov requested changes

2024-04-23 14:15 UTC, donskov commented on src/components/certificates-providers-list-item/styles/index.module.scss
> +.list_item {
Vertical indentation between elements is unnecessary. It is not on the layouts.

Implementation:
<img width="748" alt="image" src="https://github.com/PeculiarVentures/fortify-tools/assets/9417251/abacc8c6-0960-479d-a2a7-6acda60d8172">

Mockups:
<img width="956" alt="image" src="https://github.com/PeculiarVentures/fortify-tools/assets/9417251/a26f31fd-e151-4ad0-b5c5-f2163a154d20">

2024-04-23 14:15 UTC, donskov commented on src/components/certificates-providers-list-item/styles/index.module.scss
> +    background-color: var(--pv-color-primary-tint-4);
On mockups we have `tint-5`, not `tint-4`. Let's change it. 
<img width="1967" alt="image" src="https://github.com/PeculiarVentures/fortify-tools/assets/9417251/e0cd290c-ccc5-43dd-9ec1-78c26312b997">

2024-04-23 14:15 UTC, donskov commented on src/components/certificates-providers-list-item/CertificatesProvidersListItem.tsx
> +export const CertificatesProvidersListItem: React.FunctionComponent<
The component not passed text overflow test. We don't know how long the provider name can be, so we have to think about it. Let's use 3 dots at the end of the sentence if it doesn't fit in the block.

<img width="485" alt="image" src="https://github.com/PeculiarVentures/fortify-tools/assets/9417251/34e6661a-da32-41f3-8c0a-7d00b550829f">

2024-04-23 14:15 UTC, donskov commented on src/components/fetching-status-owerlay/FetchingStatusOwerlay.tsx
> +  const [element, setElement] = useState<React.ReactNode>(null);
It is at least impractical to keep react elements in the state, and at the most - incorrect work is possible when changing the state inside them (for example, changing the localization).
In this case, we can do:
```tsx
let element = null;

if (fetching.connectionClientUpdate === "rejected") {
  element = (
    <ErrorConnection
      message={t("connection.error.update-client.message")}
    />
  );
}

...
```

This example will save us from using react state.

2024-04-23 14:19 UTC, OleksandrSPV commented on src/i18n/index.ts
> +import ICU from "i18next-icu";
Do you mean ICU?

2024-04-23 14:20 UTC, donskov commented on src/i18n/index.ts
> +import ICU from "i18next-icu";
Yes

2024-04-23 14:54 UTC, OleksandrSPV commented on src/i18n/index.ts
> +import ICU from "i18next-icu";
Ok, I removed it

2024-04-23 17:17 UTC, OleksandrSPV commented on src/components/certificates-providers-list-item/CertificatesProvidersListItem.tsx
> +> = ({ provider, isSelected, onClick }) => {
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/9f94862a1ae931a01305f3dfe319425ce19f468e

2024-04-23 17:17 UTC, OleksandrSPV commented on src/components/certificates-providers-list-item/CertificatesProvidersListItem.tsx
> +  onClick?: (id: string) => void;
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/23b6dddd63d1edf1d412c63f88b1349a0c17007f

2024-04-23 17:18 UTC, OleksandrSPV commented on src/components/certificates-providers-list-item/CertificatesProvidersListItem.tsx
> +import styles from "./styles/index.module.scss";
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/4f93dda4c38751f98105f52cdf077efb38ecf5fa

2024-04-23 17:19 UTC, OleksandrSPV commented on src/components/certificates-providers-list-item/CertificatesProvidersListItem.tsx
> +        <div className={styles.list_item_name}>{provider.name}</div>
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/fc3869324bf6d5ea39d9268a1818ee86dbf3855e

2024-04-23 17:19 UTC, OleksandrSPV commented on src/components/certificates-providers-list-item/CertificatesProvidersListItem.tsx
> +    <div
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/20f793cdeb1019b9723d5a8d07d49949214cfb41

2024-04-23 17:20 UTC, OleksandrSPV commented on src/i18n/index.ts
> +import ICU from "i18next-icu";
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/cc287f40da53ff7c87661a936788fa02bf19aa33

2024-04-23 17:20 UTC, OleksandrSPV commented on src/hooks/app/useApp.tsx
> +  const getCertificatesByProviderId = async (id: string) => {
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/5c9ca39c7a6e441311632ac560d4302305a48eab

2024-04-23 17:21 UTC, OleksandrSPV commented on src/global.scss
> +@import url("https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap");
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/1f0b991644ac61f9205637a31e82ddfc05dcc08e

2024-04-23 17:24 UTC, OleksandrSPV commented on src/app.tsx
> +      {/* {certificates.map((certificate) => {
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/7e451e27d779b421b0683757099cfd06200d8569

2024-04-23 17:25 UTC, OleksandrSPV commented on src/app.tsx
> +              {/* <PeculiarCertificatesViewer
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/7e451e27d779b421b0683757099cfd06200d8569

2024-04-23 17:30 UTC, OleksandrSPV commented on src/components/certificates-list/CertificatesList.tsx
> +        <div className={styles.empty_list_text}>
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/5c7487f8a156246b43c262fd78b4d06625888c2f

2024-04-23 17:33 UTC, OleksandrSPV commented on src/components/certificates-list/CertificatesList.tsx
> +  certificates?: CertificateProp[];
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/7048f4fd3e6b671a5ccf1971eef79de32b711117

2024-04-24 14:36 UTC, OleksandrSPV commented on src/components/certificates-list/CertificatesList.tsx
> +    <div className={styles.list_root}>
Fixed [cc8f4fb](https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/cc8f4fb18475b2994ba8603fc8eacc6b3c800dfe)

2024-04-24 15:26 UTC, OleksandrSPV commented on src/components/certificates-list/CertificatesList.tsx
> +          <TableBody>
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/51c9ff7368524c46bce66c1828c9af1bc474fb9b

2024-04-24 18:44 UTC, OleksandrSPV commented on src/components/certificates-list/CertificatesList.tsx
> +                <TableCell>{notAfter.toLocaleDateString()}</TableCell>
Fixed here [b3197b8](https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/b3197b8567a451ab92b8810d7250e988f54463d1)

2024-04-25 09:34 UTC, OleksandrSPV commented on src/components/certificates-list/CertificatesList.tsx
> +                <TableCell>{notAfter.toLocaleDateString()}</TableCell>
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/8712259f87e72cf66b8a7c635a02c05a66cc863d

2024-04-25 11:37 UTC, OleksandrSPV commented on src/components/certificates-list/CertificatesList.tsx
> +  return (
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/89ba85cffbd47e9940d9440551cc8d6f76bd669d

2024-04-25 11:40 UTC, OleksandrSPV commented on src/components/certificates-list/CertificatesList.tsx
> +                <TableCell>{notAfter.toLocaleDateString()}</TableCell>
Fixed here [b3197b8](https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/b3197b8567a451ab92b8810d7250e988f54463d1)

2024-04-25 11:44 UTC, OleksandrSPV commented on src/components/certificates-providers-list/CertificatesProvidersList.tsx
> +      <div className={styles.list}>
Fixed https://github.com/PeculiarVentures/fortify-tools/commit/20f793cdeb1019b9723d5a8d07d49949214cfb41

2024-04-25 11:52 UTC, OleksandrSPV commented on src/components/certificates-providers-list/CertificatesProvidersList.tsx
> +      <div className={styles.label}>{t("providers.list.label")}</div>
Fixed [825a1da](https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/825a1dab8de9afeacee42743c0e57101f667a566)

2024-04-25 11:59 UTC, OleksandrSPV commented on src/components/certificates-sidebar/CertificatesSidebar.tsx
> +        <div>{t("sidebar.copyrigth")}</div>
Fixed here https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/73bd42225f470fd09e1684e9a55e22640032128e

2024-04-25 11:59 UTC, OleksandrSPV commented on src/components/certificates-sidebar/CertificatesSidebar.tsx
> +          <a href={APP_CONTACT_SUPPORT_URL}>{t("sidebar.contact-support")}</a>
Fixed here https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/73bd42225f470fd09e1684e9a55e22640032128e

2024-04-25 12:08 UTC, OleksandrSPV commented on src/components/certificates-providers-list-item/styles/index.module.scss
> +.list_item {
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/3c7a06254f22ef3c36c5fe47b1ad95c8f3c4b189

2024-04-25 12:08 UTC, OleksandrSPV commented on src/components/certificates-providers-list-item/styles/index.module.scss
> +    background-color: var(--pv-color-primary-tint-4);
Fixed here https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/3c7a06254f22ef3c36c5fe47b1ad95c8f3c4b189

2024-04-25 12:25 UTC, OleksandrSPV commented on src/components/certificates-providers-list-item/CertificatesProvidersListItem.tsx
> +export const CertificatesProvidersListItem: React.FunctionComponent<
Fixed [Truncate long provider name](https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/b1772bb58499f37019a0ec7692e69eb68b2821ac)

2024-04-25 13:37 UTC, OleksandrSPV commented on src/components/fetching-status-owerlay/FetchingStatusOwerlay.tsx
> +  const [element, setElement] = useState<React.ReactNode>(null);
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/eabbcb5d576dfed197ebab765e37cd125a53c1f8

2024-04-29 11:32 UTC, donskov requested changes

2024-04-29 11:32 UTC, donskov commented on src/components/certificates-providers-list/styles/index.module.scss
> +.list_box_wrapper {
We should try to follow the rule that the scrollbar should be as close as possible to one of the sides and not be in the air. It is very nice to test if you connect the mouse and the scrollbar becomes static.

<img width="402" alt="Screenshot 2024-04-29 at 14 23 14" src="https://github.com/PeculiarVentures/fortify-tools/assets/9417251/69977de7-3f95-4858-adb4-70789579a062">

2024-04-29 11:32 UTC, donskov commented on src/components/certificates-list/styles/index.module.scss
> +.list_table {
The certificates list table has not equal padding.

<img width="1512" alt="Screenshot 2024-04-29 at 14 29 12" src="https://github.com/PeculiarVentures/fortify-tools/assets/9417251/947e3a60-3a9f-44b6-8e05-7c4f661a0c64">

2024-04-29 11:38 UTC, donskov requested changes

2024-04-29 11:38 UTC, donskov commented on src/app.tsx
> +      <div className={styles.top_bar}></div>
I think that in this version we should also make a header that is in the design (so far without functionality such as search).

Current result:
<img width="1512" alt="image" src="https://github.com/PeculiarVentures/fortify-tools/assets/9417251/d073f4b5-0caf-4f12-a8b9-b2b8815dcd23">

Mockup:
<img width="692" alt="image" src="https://github.com/PeculiarVentures/fortify-tools/assets/9417251/3c8f2e79-fd5a-440f-94e5-c30371002d4f">

2024-04-29 11:48 UTC, donskov requested changes

2024-04-29 11:48 UTC, donskov commented on src/components/certificates-list/styles/index.module.scss
> +.list_table {
The table header and body text are not aligned vertically.

<img width="1076" alt="Screenshot 2024-04-29 at 14 39 37" src="https://github.com/PeculiarVentures/fortify-tools/assets/9417251/68901102-53ba-4627-ab4d-c19e168af2f2">

2024-04-29 11:53 UTC, donskov requested changes

2024-04-29 11:53 UTC, donskov commented on src/components/certificates-sidebar/CertificatesSidebar.tsx
> +      <div className={styles.footer}>
We have a small problem related to the default inline element size. The next image illustrates it. This may be resolved by adding `font-size: 0` to the parent element.

<img width="408" alt="image" src="https://github.com/PeculiarVentures/fortify-tools/assets/9417251/c3e0e98e-9f59-4147-8c79-b3c22642f421">

2024-04-29 11:56 UTC, OleksandrSPV commented on src/components/certificates-list/styles/index.module.scss
> +.list_table {
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/51fa643fc8e3723053931b86bec993483bb24940

2024-04-29 11:56 UTC, donskov requested changes

2024-04-29 11:56 UTC, donskov commented on src/components/certificates-list/styles/index.module.scss
> +.list_table {
Also, the row table text is not aligned horizontally.

<img width="1168" alt="Screenshot 2024-04-29 at 14 55 06" src="https://github.com/PeculiarVentures/fortify-tools/assets/9417251/a97e88b4-1daa-417b-9e88-bc6ec47fe644">

2024-04-29 12:12 UTC, OleksandrSPV commented on src/components/certificates-list/styles/index.module.scss
> +.list_table {
Fixed [1a72766](https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/1a72766141196365951e63d6f9de60791c111378)

2024-04-29 12:16 UTC, OleksandrSPV commented on src/components/certificates-list/styles/index.module.scss
> +.list_table {
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/7df5aa7abe648b9872ab1353dbd43b6c3754c9b6

2024-04-29 12:23 UTC, OleksandrSPV commented on src/components/certificates-providers-list/styles/index.module.scss
> +.list_box_wrapper {
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/cc2e28ef1dcf5fd98d4abcc508d71cd7f5cd164e

2024-04-29 14:32 UTC, OleksandrSPV commented on src/app.tsx
> +      <div className={styles.top_bar}></div>
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/101/commits/5a3d1edb3718b709c17392fb8dbbf96a4a4fc1c3

2024-04-29 15:01 UTC, merged