Version 2: Add delete certificate dialog
PeculiarVentures/fortify-tools pull request #130
Opened 2024-05-01 14:44 UTC by OleksandrSPV

2024-05-03 08:39 UTC, donskov requested changes

2024-05-03 08:39 UTC, donskov commented on src/components/certificate-delete-button/CertificateDeleteButton.tsx
> +      <IconButton
It's better to use the `title` prop instead of using `Tooltip`. The `IconButton` has it especially for resolving this case.

2024-05-03 08:39 UTC, donskov commented on src/components/certificate-delete-button/CertificateDeleteButton.tsx
> +export const CertificateDeleteButton: React.FunctionComponent<
I don't see the point in making a separate component for this case. We do not add any specific logic. In my opinion, it is better not to complicate things and add the rendering of the button directly to the place where it is needed.

2024-05-03 08:39 UTC, donskov commented on src/components/certificate-delete-dialog/styles/index.module.scss
> +.dialog {
The title and text are not aligned vertically.

Mockup:
<img width="863" alt="image" src="https://github.com/PeculiarVentures/fortify-tools/assets/9417251/7f9c5a12-b03c-4e07-85b3-b420998af848">

Current result:
<img width="1219" alt="Screenshot 2024-05-03 at 11 17 58" src="https://github.com/PeculiarVentures/fortify-tools/assets/9417251/484e443d-1893-445a-b665-0f687d3a368d">

2024-05-03 08:39 UTC, donskov commented on src/components/certificate-delete-dialog/CertificateDeleteDialog.tsx
> +      open={!!certificateId}
We can't control the dialog opening state by the `certificateId` prop because it's not clear. This prop is required and hard to understand that the developer should pass an empty string to hide the dialog. Let's use always `open: true` and move control visibility to the parent component.

2024-05-03 08:39 UTC, donskov commented on src/components/certificate-delete-dialog/styles/index.module.scss
> +    > div:nth-child(2) {
It seems to me (and I've read about it more than once) that adding styles per tag is a bad practice. At any moment the tag can change and this will lead to the fact that our page will be broken. Let's use classes as we did before.

2024-05-03 08:39 UTC, donskov commented on src/components/certificates-list/styles/index.module.scss
> +      > button {
It seems to me (and I've read about it more than once) that adding styles per tag is a bad practice. At any moment the tag can change and this will lead to the fact that our page will be broken. Let's use classes as we did before.

2024-05-03 08:39 UTC, donskov commented on src/components/certificates-list/styles/index.module.scss
> +          margin-right: var(--pv-size-base-2);
The distance between the elements does not match the distance on the mockup.

<img width="718" alt="Screenshot 2024-05-03 at 11 35 41" src="https://github.com/PeculiarVentures/fortify-tools/assets/9417251/9ee413f1-8a8f-424b-a875-88adfc3b05b7">

2024-05-03 08:39 UTC, donskov commented on src/components/certificates-list/styles/index.module.scss
>      &:hover .list_table_actions {
The certificate list element fails the accessibility test. Using the keyboard, I can't figure out which item is highlighted and delete the certificate.

2024-05-03 12:29 UTC, OleksandrSPV commented on src/components/certificate-delete-button/CertificateDeleteButton.tsx
> +export const CertificateDeleteButton: React.FunctionComponent<
Fixed [a75d2cd](https://github.com/PeculiarVentures/fortify-tools/pull/130/commits/a75d2cdf90038cfcbfe4a974c99edbdbdf5a947b)

2024-05-03 12:34 UTC, OleksandrSPV commented on src/components/certificate-delete-dialog/CertificateDeleteDialog.tsx
> +      open={!!certificateId}
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/130/commits/0b1b51efdc68d14db7e1751d382e663748c02c45

2024-05-03 13:40 UTC, OleksandrSPV commented on src/components/certificates-list/styles/index.module.scss
> +          margin-right: var(--pv-size-base-2);
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/130/commits/1992b65f7df295cd6226864dd918d489ee1756ce

2024-05-03 13:40 UTC, OleksandrSPV commented on src/components/certificates-list/styles/index.module.scss
> +      > button {
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/130/commits/1992b65f7df295cd6226864dd918d489ee1756ce

2024-05-03 13:53 UTC, OleksandrSPV commented on src/components/certificate-delete-dialog/styles/index.module.scss
> +    > div:nth-child(2) {
Fix https://github.com/PeculiarVentures/fortify-tools/pull/130/commits/c91e8d7540047c54f8506ae83a3bb3513a1e6826

2024-05-03 14:02 UTC, OleksandrSPV commented on src/components/certificate-delete-dialog/styles/index.module.scss
> +.dialog {
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/130/commits/38f6f4d53a30e87e4c8a382b09c1b29210cf6e9b

2024-05-03 15:05 UTC, OleksandrSPV commented on src/components/certificates-list/styles/index.module.scss
>      &:hover .list_table_actions {
Fixed https://github.com/PeculiarVentures/fortify-tools/pull/130/commits/772bbd1e95a2ee8c499b96f51609f7cf81abd22d

2024-05-06 11:31 UTC, donskov approved these changes

2024-05-06 11:31 UTC, merged