Version 2: Add App error boundary
PeculiarVentures/fortify-tools pull request #148
Opened 2024-05-30 13:34 UTC by OleksandrSPV

2024-06-04 13:50 UTC, donskov requested changes

2024-06-04 13:50 UTC, donskov commented on src/components/error-boundary/ErrorBoundary.ts
> +export class ErrorBoundary extends Component<
Does it make sense to use such complex code to solve a small problem? It is important for us only to catch the error and show it so that we know what the problem is (make it render or show it in the console).

2024-06-04 13:50 UTC, donskov commented on src/components/app-fallback/AppFallback.tsx
> +import { useTranslation } from "react-i18next";
Pay attention to the sorting of imports. We use a linter rule to automate this.
Rule page - https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/order.md

2024-06-04 13:57 UTC, OleksandrSPV commented on src/components/error-boundary/ErrorBoundary.ts
> +export class ErrorBoundary extends Component<
Actually I am planning switch to this https://react.dev/reference/react-dom/client/createRoot#displaying-error-boundary-errors when it will be available, but now I use classical way

2024-06-04 14:39 UTC, donskov commented on src/components/app-fallback/AppFallback.tsx
> +import { useTranslation } from "react-i18next";
It will be better to add this rule to our list so that we do not repeat it in the future.

2024-06-04 14:40 UTC, donskov commented on src/components/error-boundary/ErrorBoundary.ts
> +export class ErrorBoundary extends Component<
But the problem has not been solved. What will we do with this decision?

2024-06-04 14:43 UTC, OleksandrSPV commented on src/components/app-fallback/AppFallback.tsx
> +import { useTranslation } from "react-i18next";
I am working on it, the issue is we use eslint v9, and I need time to figure out on it, will add in separate PR

2024-06-05 12:05 UTC, donskov commented on src/components/error-boundary/ErrorBoundary.ts
> +export class ErrorBoundary extends Component<
@OleksandrSPV I see that the code is the same as https://www.npmjs.com/package/react-error-boundary. Let's use that module and remove own implementation.

2024-06-05 12:08 UTC, OleksandrSPV commented on src/components/error-boundary/ErrorBoundary.ts
> +export class ErrorBoundary extends Component<
Ok, no problem, I'll do it

2024-06-05 14:16 UTC, OleksandrSPV commented on src/components/error-boundary/ErrorBoundary.ts
> +export class ErrorBoundary extends Component<
Fixed here https://github.com/PeculiarVentures/fortify-tools/pull/148/commits/29937742477ca092a02b95fa5a3b1348d5b22549

2024-06-06 08:57 UTC, donskov approved these changes

2024-06-06 08:57 UTC, merged

2024-06-06 10:46 UTC, OleksandrSPV commented on src/components/app-fallback/AppFallback.tsx
> +import { useTranslation } from "react-i18next";
@donskov What order do you prefer? I propose to use rules as default
`"import/order": [
        "error",
        {
          groups: ["builtin", "external", "parent", "sibling", "index"],
        },
      ],`
      If you have any other propositions about this, please let me know.

2024-06-06 13:21 UTC, donskov commented on src/components/app-fallback/AppFallback.tsx
> +import { useTranslation } from "react-i18next";
Let's use rules from our projects:
`'import/order': ['error', { groups: [['builtin', 'external', 'internal']] }],`