Version 2: Add certificate creation logic
PeculiarVentures/fortify-tools pull request #149
Opened 2024-05-31 11:44 UTC by OleksandrSPV

2024-06-06 13:27 UTC, donskov requested changes

2024-06-06 13:27 UTC, donskov commented on src/hooks/app/useApp.tsx
> +  const handleAddCSRToList = (
We don't need this extra code. Let's reload the list of certificates and in feature, we will add CSR support.

2024-06-06 13:27 UTC, donskov commented on src/dialogs/certificate-create-dialog/useCertificateCreateDialog.tsx
> +  fortifyClient: FortifyAPI | null;
The hook can't work if the `fortifyClient` prop is not defined.

2024-06-06 13:34 UTC, OleksandrSPV commented on src/hooks/app/useApp.tsx
> +  const handleAddCSRToList = (
Ok, deal

2024-06-06 14:17 UTC, OleksandrSPV commented on src/hooks/app/useApp.tsx
> +  const handleAddCSRToList = (
Removed here https://github.com/PeculiarVentures/fortify-tools/pull/149/commits/ba3030083b7ffd242494e4077bba9baa386c5203

2024-06-06 14:17 UTC, OleksandrSPV commented on src/dialogs/certificate-create-dialog/useCertificateCreateDialog.tsx
> +  fortifyClient: FortifyAPI | null;
Fixed here https://github.com/PeculiarVentures/fortify-tools/pull/149/commits/ba3030083b7ffd242494e4077bba9baa386c5203

2024-06-24 11:18 UTC, donskov requested changes

2024-06-24 11:18 UTC, donskov commented on src/dialogs/certificate-create-dialog/useCertificateCreateDialog.tsx
> +            hashAlgorithm: algorithm?.hash as EHashAlgorithm,
I don't see any gap to make these variables required and prevent using `as`. Any thoughts?

2024-06-24 11:33 UTC, OleksandrSPV commented on src/dialogs/certificate-create-dialog/useCertificateCreateDialog.tsx
> +            hashAlgorithm: algorithm?.hash as EHashAlgorithm,
@donskov Fixed here https://github.com/PeculiarVentures/fortify-tools/pull/149/commits/604e624eb1a7d4d0ab20e005e8a5065b72656c04

2024-06-24 11:33 UTC, OleksandrSPV commented on src/dialogs/certificate-create-dialog/useCertificateCreateDialog.tsx
> +            hashAlgorithm: algorithm?.hash as EHashAlgorithm,
@donskov Fixed here https://github.com/PeculiarVentures/fortify-tools/pull/149/commits/604e624eb1a7d4d0ab20e005e8a5065b72656c04

2024-06-24 13:08 UTC, donskov approved these changes

2024-06-24 13:09 UTC, merged