Version 2: Fix certificate import dialog
PeculiarVentures/fortify-tools pull request #150
Opened 2024-06-03 14:22 UTC by OleksandrSPV

2024-06-06 13:37 UTC, donskov requested changes

2024-06-06 13:37 UTC, donskov commented on src/utils/certificate.ts
> +export const isHex = (value: string) =>
We have the `Convert.isHex` utility. Let's use it.

2024-06-06 13:37 UTC, donskov commented on src/utils/certificate.ts
> +export const isBase64 = (value: string) => {
We have the `Convert.isBase64` utility. Let's use it.

2024-06-06 13:42 UTC, donskov requested changes

2024-06-06 13:42 UTC, donskov commented on src/utils/certificate.ts
> +export function certificateConvertRaw(cert: string | ArrayBuffer): ArrayBuffer {
Maybe we can use something like this https://github.com/PeculiarVentures/x509/blob/3a8fd4628be15cf96dfcd2f84173e82155f898d5/src/pem_data.ts#L9 instead. It includes the same functionality.

2024-06-06 13:54 UTC, OleksandrSPV commented on src/utils/certificate.ts
> +export function certificateConvertRaw(cert: string | ArrayBuffer): ArrayBuffer {
Thanks, looks good, I'll check

2024-06-06 15:11 UTC, OleksandrSPV commented on src/utils/certificate.ts
> +export function certificateConvertRaw(cert: string | ArrayBuffer): ArrayBuffer {
@donskov I tried to use Convert.isHex & Convert.isBase64 and it doesn't work for me. I understand now why guys from Goodkey didn't use it. Do you have any ideas?

2024-06-06 15:35 UTC, OleksandrSPV commented on src/utils/certificate.ts
> +export function certificateConvertRaw(cert: string | ArrayBuffer): ArrayBuffer {
@donskov I've improved the converter method a bit here https://github.com/PeculiarVentures/fortify-tools/pull/150/commits/99549579e2c208169466b9b06931f07d483f9a86, but the previous question is still relevant.

2024-06-27 13:43 UTC, donskov requested changes

2024-06-27 13:43 UTC, donskov commented on src/dialogs/certificate-import-dialog/useCertificateImportDialog.tsx
> +    const buf = certificateConvertRaw(fileContent);
I'm trying to figure out what exactly we need this function for. The `X509Certificate` class has checks to transpile input to the correct value.

Just tried `console.log("drop", new X509Certificate(fileContent));` without any extra transformations and see the correct output. Any thoughts?

2024-06-27 15:23 UTC, OleksandrSPV commented on src/dialogs/certificate-import-dialog/useCertificateImportDialog.tsx
> +    const buf = certificateConvertRaw(fileContent);
@donskov fixed here https://github.com/PeculiarVentures/fortify-tools/pull/150/commits/23dbd4fce74773f0c5f26481e8e2ca9fb8475ffd

2024-07-04 08:21 UTC, donskov approved these changes

2024-07-04 08:21 UTC, merged