Remove certificate logic
PeculiarVentures/fortify-tools pull request #152
Opened 2024-06-10 11:39 UTC by OleksandrSPV

One think, maybe we should merge this PR first https://github.com/PeculiarVentures/fortify-tools/pull/149 to have possibility to reload certificate list

2024-06-24 11:31 UTC, donskov requested changes

2024-06-24 11:31 UTC, donskov commented on src/dialogs/certificate-delete-dialog/useCertificateDeleteDialog.tsx
> +  fortifyClient?: FortifyAPI | null;
I don't think that the `fortifyClient` parameter can be optional. Without it, we can't finish the delete operation. Let's make it required.

2024-06-24 11:31 UTC, donskov commented on src/dialogs/certificate-delete-dialog/useCertificateDeleteDialog.tsx
>    const [currentCertificatDelete, setCurrentCetificateDelete] = React.useState<
Since we do not update this data, but only save it for further use, we can eliminate the use of state. Also, we should double-add typings for the state and the open function.
Note the following entry (skip naming, it's related to the other project):
```tsx
type UseRemoveUserDialogInitialParams = {
  onRequestSuccess: () => void;
};

type UseRemoveUserDialogOpenParams = {
  user: IUser;
};

export const useRemoveUserDialog = (
  initialParams: UseRemoveUserDialogInitialParams,
) => {
  const [open, setOpen] = React.useState(false);
  const openParamsRef = React.useRef<UseRemoveUserDialogOpenParams>();

  const handleOpen = (params: UseRemoveUserDialogOpenParams) => {
    openParamsRef.current = params;

    setOpen(true);
  };

  const handleClose = () => {
    setOpen(false);

    openParamsRef.current = undefined;
  };

  ...
};
```

2024-06-24 12:19 UTC, OleksandrSPV commented on src/dialogs/certificate-delete-dialog/useCertificateDeleteDialog.tsx
> +  fortifyClient?: FortifyAPI | null;
Fixed here https://github.com/PeculiarVentures/fortify-tools/pull/152/commits/58213a1e62e8dbb098e76ec07f5c425ed4b7b253

2024-06-24 12:19 UTC, OleksandrSPV commented on src/dialogs/certificate-delete-dialog/useCertificateDeleteDialog.tsx
>    const [currentCertificatDelete, setCurrentCetificateDelete] = React.useState<
Fixed here https://github.com/PeculiarVentures/fortify-tools/pull/152/commits/58213a1e62e8dbb098e76ec07f5c425ed4b7b253

2024-06-24 13:05 UTC, donskov commented on src/dialogs/certificate-delete-dialog/useCertificateDeleteDialog.tsx
>    const [currentCertificatDelete, setCurrentCetificateDelete] = React.useState<
@OleksandrSPV The `handleOpen` function argument can be also typed by `UseCertificateDeleteDialogOpenParams`.

2024-06-24 13:07 UTC, donskov commented on src/dialogs/certificate-delete-dialog/useCertificateDeleteDialog.tsx
> +  fortifyClient?: FortifyAPI | null;
Not fixed because we allow it to pass `null`.

2024-06-24 13:44 UTC, OleksandrSPV commented on src/dialogs/certificate-delete-dialog/useCertificateDeleteDialog.tsx
>    const [currentCertificatDelete, setCurrentCetificateDelete] = React.useState<
Fixed here https://github.com/PeculiarVentures/fortify-tools/pull/152/commits/d1896245808d03018431a97dbe7d43eb38a8decb

2024-06-27 13:33 UTC, donskov commented on src/dialogs/certificate-delete-dialog/useCertificateDeleteDialog.tsx
> +  fortifyClient?: FortifyAPI | null;
@OleksandrSPV Any progress?

2024-06-27 13:36 UTC, OleksandrSPV commented on src/dialogs/certificate-delete-dialog/useCertificateDeleteDialog.tsx
> +  fortifyClient?: FortifyAPI | null;
@donskov Ops! I messed previous message. Checking now, sorry.

2024-06-27 14:04 UTC, OleksandrSPV commented on src/dialogs/certificate-delete-dialog/useCertificateDeleteDialog.tsx
> +  fortifyClient?: FortifyAPI | null;
@donskov fixed here https://github.com/PeculiarVentures/fortify-tools/pull/152/commits/384e8cf78f1c98b6898fde17cc85fcd8d05f380d

2024-06-27 14:49 UTC, donskov approved these changes

2024-06-27 14:49 UTC, merged