Version2: Add certificate search logic
PeculiarVentures/fortify-tools pull request #167
Opened 2024-07-04 16:01 UTC by OleksandrSPV

https://github.com/PeculiarVentures/fortify-tools/assets/129727832/f4ce0374-2b5e-4a95-b82b-aaf9e3612bcc

2024-07-11 11:34 UTC, donskov requested changes

2024-07-11 11:34 UTC, donskov commented on src/hooks/search-list/useSearchList.tsx
> +  const searchParams = new URLSearchParams(window.location.search);
We need to use the `searchParams` only for default state prefilling, but this code calls on each rerender. We have to fix this and parse parameters only 1 time.

2024-07-11 11:34 UTC, donskov commented on src/hooks/search-list/useSearchList.tsx
> +      ? certificates.filter(({ label }) =>
It's the same situation with multiple re-renders. We should try to make filtration only when the `searchedText` or the `certificates` have changed. Now, even when opening a dialog, we filter certificates.

2024-07-11 11:40 UTC, donskov commented
@OleksandrSPV Not related to these changes, but is there any reason to have the search state in the search hook and two search states in the [component](https://github.com/PeculiarVentures/fortify-tools/blob/donskov/v2/src/components/certificates-topbar/CertificatesTopbar.tsx#L34-L35)? Can we use only a single source of truth?

2024-07-15 12:22 UTC, OleksandrSPV commented on src/hooks/search-list/useSearchList.tsx
> +  const searchParams = new URLSearchParams(window.location.search);
@donskov Fixed here https://github.com/PeculiarVentures/fortify-tools/pull/167/commits/3de8b750b325d4703ad0f8c94cf521823f848876

2024-07-15 12:22 UTC, OleksandrSPV commented on src/hooks/search-list/useSearchList.tsx
> +      ? certificates.filter(({ label }) =>
@donskov Fixed here https://github.com/PeculiarVentures/fortify-tools/pull/167/commits/3de8b750b325d4703ad0f8c94cf521823f848876

2024-07-15 12:23 UTC, OleksandrSPV commented
> @OleksandrSPV Not related to these changes, but is there any reason to have the search state in the search hook and two search states in the [component](https://github.com/PeculiarVentures/fortify-tools/blob/donskov/v2/src/components/certificates-topbar/CertificatesTopbar.tsx#L34-L35)? Can we use only a single source of truth?

@donskov I needed to use delayed input, so I decided use this part near the input component not in search hook. If you have some proposition, please let me know.

2024-07-16 08:56 UTC, donskov commented
> > @OleksandrSPV Not related to these changes, but is there any reason to have the search state in the search hook and two search states in the [component](https://github.com/PeculiarVentures/fortify-tools/blob/donskov/v2/src/components/certificates-topbar/CertificatesTopbar.tsx#L34-L35)? Can we use only a single source of truth?
> 
> @donskov I needed to use delayed input, so I decided use this part near the input component not in search hook. As I see guys on Goodkey don't use input delay for certificate search, we can go this way if you prefer, and remove one state from search component, or if you have another proposition, please let me know.

Yeah, let's remove it.

2024-07-16 09:17 UTC, OleksandrSPV commented
> > > @OleksandrSPV Not related to these changes, but is there any reason to have the search state in the search hook and two search states in the [component](https://github.com/PeculiarVentures/fortify-tools/blob/donskov/v2/src/components/certificates-topbar/CertificatesTopbar.tsx#L34-L35)? Can we use only a single source of truth?
> > 
> > 
> > @donskov I needed to use delayed input, so I decided use this part near the input component not in search hook. As I see guys on Goodkey don't use input delay for certificate search, we can go this way if you prefer, and remove one state from search component, or if you have another proposition, please let me know.
> 
> Yeah, let's remove it.

@donskov removed here https://github.com/PeculiarVentures/fortify-tools/pull/167/commits/93c9ee78a122b89aa091333903ab4a75aa9ec284

2024-07-16 11:03 UTC, donskov commented
> > > > @OleksandrSPV Not related to these changes, but is there any reason to have the search state in the search hook and two search states in the [component](https://github.com/PeculiarVentures/fortify-tools/blob/donskov/v2/src/components/certificates-topbar/CertificatesTopbar.tsx#L34-L35)? Can we use only a single source of truth?
> > > 
> > > 
> > > @donskov I needed to use delayed input, so I decided use this part near the input component not in search hook. As I see guys on Goodkey don't use input delay for certificate search, we can go this way if you prefer, and remove one state from search component, or if you have another proposition, please let me know.
> > 
> > 
> > Yeah, let's remove it.
> 
> @donskov removed here [93c9ee7](https://github.com/PeculiarVentures/fortify-tools/commit/93c9ee78a122b89aa091333903ab4a75aa9ec284)

Do we also need the search input state (`const [searchInputValue, setSearchInputValue] = React.useState(searchValue);`)?

2024-07-16 11:12 UTC, OleksandrSPV commented
> 235b1fd

@donskov oops, actually don't, fixed here

2024-07-22 09:16 UTC, donskov approved these changes

2024-07-22 09:16 UTC, merged