Version 2: Add tests for certificate creation components
PeculiarVentures/fortify-tools pull request #185
Opened 2024-08-01 16:00 UTC by OleksandrSPV

2024-08-05 12:17 UTC, donskov requested changes

2024-08-05 12:17 UTC, donskov commented on src/components/certificate-create-by-cname/CertificateCreateByCname.test.tsx
> +import { describe, it, render, vi, expect, userEvent } from "@testing";
I can see a way to reduce code writing and import standard utilities for testing (`describe/it/expect`). Just enable [global](https://vitest.dev/config/#globals) vitest and utils will be available in the global scope without import.

2024-08-05 12:26 UTC, OleksandrSPV commented on src/components/certificate-create-by-cname/CertificateCreateByCname.test.tsx
> +import { describe, it, render, vi, expect, userEvent } from "@testing";
@donskov sure, no problem, I'll do it

2024-08-05 12:31 UTC, donskov requested changes

2024-08-05 12:31 UTC, donskov commented on src/components/certificate-create-by-email/CertificateCreateByEmail.test.tsx
> +afterEach(cleanup);
Any reason to use the `cleanup` each time? It should only be used where necessary

2024-08-05 12:31 UTC, donskov commented on src/dialogs/certificate-create-dialog/useCertificateCreateDialog.test.tsx
> +    expect(mockFortifyClient.createX509).toHaveBeenCalled();
Since this hook contains the data configuration logic when calling the Fortify interface, we need to check with which arguments we did it.

2024-08-05 12:37 UTC, OleksandrSPV commented on src/components/certificate-create-by-cname/CertificateCreateByCname.test.tsx
> +import { describe, it, render, vi, expect, userEvent } from "@testing";
@donskov fixed here https://github.com/PeculiarVentures/fortify-tools/pull/185/commits/bad153d5e4093c1f36696d83bbc05ae7b5d9500a

2024-08-05 12:45 UTC, OleksandrSPV commented on src/components/certificate-create-by-email/CertificateCreateByEmail.test.tsx
> +afterEach(cleanup);
@donskov fixed here https://github.com/PeculiarVentures/fortify-tools/pull/185/commits/7403e1a757efcb7618a91c1a11c83dd791d379bb

2024-08-05 12:53 UTC, OleksandrSPV commented on src/dialogs/certificate-create-dialog/useCertificateCreateDialog.test.tsx
> +    expect(mockFortifyClient.createX509).toHaveBeenCalled();
@donskov fixed here https://github.com/PeculiarVentures/fortify-tools/pull/185/commits/03a4c00ddcff24a12b66ac18a04ea8fb03630f7d

2024-08-05 13:14 UTC, donskov requested changes

2024-08-05 13:14 UTC, donskov commented on src/components/key-usages-checkbox-group/KeyUsagesCheckboxGroup.test.tsx
> +describe("<KeyUsagesCheckboxGroup />", () => {
Unfortunately, the component has not been fully tested. If, for example, you replace the values ​​of the checkboxes with other values, then the test will pass, but the global creation of the certificate will be broken.

Alternatively we could check it as follows (or your option):
```tsx
const checkboxElements = screen.getAllByRole("checkbox");

expect(checkboxElements.map((el) => el.getAttribute("name"))).toEqual([
  "keyUsage",
  "keyUsage",
  "keyUsage",
  "keyUsage",
  "keyUsage",
]);
expect(checkboxElements.map((el) => el.getAttribute("value"))).toEqual([
  "1.3.6.1.5.5.7.3.4",
  "1.3.6.1.5.5.7.3.3",
  "1.3.6.1.5.5.7.3.36",
  "1.3.6.1.5.5.7.3.2",
  "1.3.6.1.5.5.7.3.1",
]);
```

2024-08-05 13:39 UTC, OleksandrSPV commented on src/components/key-usages-checkbox-group/KeyUsagesCheckboxGroup.test.tsx
> +describe("<KeyUsagesCheckboxGroup />", () => {
@donskov fixed here https://github.com/PeculiarVentures/fortify-tools/pull/185/commits/71516b2c7bfd5f74426b12947209c6042130739e

2024-08-06 08:26 UTC, donskov requested changes

2024-08-06 08:26 UTC, donskov commented on src/components/certificate-type-select/CertificateTypeSelect.test.tsx
> +    const handleChange = vi.fn((data) => data);
I can see that this code works, but we can use a different way of validation and not return the function arguments every time.
```tsx
const handleChange = vi.fn();
...
expect(handleChange).toBeCalledWith({
  label: "Custom certificate",
  value: "custom",
});
```

2024-08-06 08:26 UTC, donskov commented on src/components/certificate-type-select/CertificateTypeSelect.test.tsx
> +    expect(comboboxItems[5]).toHaveTextContent(/Custom certificate/);
As with the KeyUsagesCheckboxGroup component, these tests do not check which options are present in the dropdown list. We have to check this because it is an important functionality for the whole application.

2024-08-06 08:26 UTC, donskov commented on src/components/certificate-key-properties-select/CertificateKeyPropertiesSelect.test.tsx
> +    expect(combobox0Items).toHaveLength(5);
Better to check what exactly options we show instead of their count.
```tsx
expect(combobox0Items.map((el) => el.textContent)).toEqual([
  "RSA-2048",
  "RSA-4096",
  "EC-P256",
  "EC-P384",
  "EC-P521",
]);
```

2024-08-06 08:36 UTC, OleksandrSPV commented on src/components/certificate-type-select/CertificateTypeSelect.test.tsx
> +    const handleChange = vi.fn((data) => data);
@donskov i don't understand, could you please explain more?

2024-08-06 08:36 UTC, OleksandrSPV commented on src/components/certificate-type-select/CertificateTypeSelect.test.tsx
> +    expect(comboboxItems[5]).toHaveTextContent(/Custom certificate/);
@donskov ok, will do this

2024-08-06 09:25 UTC, OleksandrSPV commented on src/components/certificate-type-select/CertificateTypeSelect.test.tsx
> +    const handleChange = vi.fn((data) => data);
@donskov Is it right way? https://github.com/PeculiarVentures/fortify-tools/pull/185/commits/b0709bd3fa96415ecaf830570ebac40ba51fbeda

2024-08-06 09:26 UTC, OleksandrSPV commented on src/components/certificate-type-select/CertificateTypeSelect.test.tsx
> +    expect(comboboxItems[5]).toHaveTextContent(/Custom certificate/);
@donskov fixed here https://github.com/PeculiarVentures/fortify-tools/pull/185/commits/b0709bd3fa96415ecaf830570ebac40ba51fbeda

2024-08-06 09:37 UTC, OleksandrSPV commented on src/components/certificate-key-properties-select/CertificateKeyPropertiesSelect.test.tsx
> +    expect(combobox0Items).toHaveLength(5);
@donskov fixed here https://github.com/PeculiarVentures/fortify-tools/pull/185/commits/2fda6e1cf06bfee707c2d48bc8f34ccc4e1a2328

2024-09-12 12:01 UTC, donskov requested changes

2024-09-12 12:01 UTC, donskov commented on src/components/certificate-create-by-cname/CertificateCreateByCname.test.tsx
> +describe("<CertificateCreateByCname />", () => {
I have worked a little on this test and I propose to consider the option of how we can simplify it:

```tsx
import { render, vi, userEvent, screen } from "@testing";
import { CertificateCreateByCname } from "./CertificateCreateByCname";

describe("<CertificateCreateByCname />", () => {
  const createDataResult = {
    subject: { CN: "example.com" },
    algorithm: { hash: "SHA-256", signature: "RSA-2048" },
    type: "x509",
  };

  it("Should render & submit", async () => {
    const onCreateButtonClickMock = vi.fn();

    render(
      <CertificateCreateByCname
        type="x509"
        onCreateButtonClick={onCreateButtonClickMock}
      />
    );

    const buttonElement = screen.getByRole("button", { name: "Create certificate" });
    expect(buttonElement).toBeDisabled();

    await userEvent.type(
      screen.getByRole("textbox", { name: "Common name", }),
      createDataResult.subject.CN,
    );
    await userEvent.click(buttonElement);

    expect(onCreateButtonClickMock).toBeCalledTimes(1);
    expect(onCreateButtonClickMock).toBeCalledWith(createDataResult);
  });
});

```

Main differences:
1. Use `screen.getByRole` instead of `getByRole` directly from the render result for querying DOM elements, ensuring better readability and reducing destructuring in tests.
2. Change `handleCreate` to `onCreateButtonClickMock` for clarity and consistency with common mock naming conventions.
3. Omit unnecessary assertions like `expect(cnFieldElement).toBeInTheDocument()` or `expect(button).toBeInTheDocument()`, as querying methods like `getByRole` already handle this. Focus on the behavior that matters for the test.
4. Update the check for the mock function to `expect(onCreateButtonClickMock).toBeCalledWith(createDataResult)` for clarity and maintainability.
5. Move the mock return data for `handleCreate` into a constant (like `createDataResult`) to reduce repetition and enhance code clarity.

2024-09-12 18:50 UTC, OleksandrSPV commented on src/components/certificate-create-by-cname/CertificateCreateByCname.test.tsx
> +describe("<CertificateCreateByCname />", () => {
Fixed, please check @donskov

2024-09-17 13:53 UTC, donskov approved these changes

2024-09-17 13:53 UTC, merged